import { createStats, createImage, createEquipmentItem } from './funkceTabulkos.js';

  export const kamenyData = [      
      createEquipmentItem(10, 'Kámen průniku', 'https://img.m2icondb.com/28000.png', '', {
        R_1:  createStats("Šance na pronikavý zásah:",  "1%", "2%", "3%", "5%", "8%", "10%", "13%", "-", "-", "-"),
        R_11: createStats("Šance na brutální zásah:",            "-", "-", "-", "-", "-", "-", "-", "2%", "4%", "7%"),
        R_M1: createStats(),
        R_2: createStats("Šance:",  "-", "-", "-", "-", "-", "-", "-",          "10%",    "10%",   "5%"),
        R_3: createStats("Cena:",   "-", "-", "-", "-", "-", "-", "-",          "2kkk",   "3kkk",  "5kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:",  "", "", "", "", "", "", "",     "192x",   "256x",   "384x"),
        R_5: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
        R_6: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_11: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "", "", "", "", "", "./items/Střelný prach.png", "./items/Střelný prach.png", "./items/Střelný prach.png"),
        IMG_5: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png"),
        IMG_6: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png"),
      }),
      createEquipmentItem(10, 'Kámen smrtelné rány', 'https://img.m2icondb.com/28001.png', '', {
        R_1:  createStats("Šance na kritický zásah:",  "1%", "2%", "3%", "5%", "8%", "10%", "13%", "-", "-", "-"),
        R_11: createStats("Průměrná škoda:",            "-", "-", "-", "-", "-", "-", "-", "2%", "4%", "7%"),
        R_M1: createStats(),
        R_2: createStats("Šance:",  "-", "-", "-", "-", "-", "-", "-",          "10%",    "10%",   "5%"),
        R_3: createStats("Cena:",   "-", "-", "-", "-", "-", "-", "-",          "2kkk",   "3kkk",  "5kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:",  "", "", "", "", "", "", "",     "192x",   "256x",   "384x"),
        R_5: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
        R_6: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_11: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "", "", "", "", "", "./items/Střelný prach.png", "./items/Střelný prach.png", "./items/Střelný prach.png"),
        IMG_5: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png"),
        IMG_6: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png"),
      }),
      createEquipmentItem(10, 'Kámen návratu', 'https://img.m2icondb.com/28002.png', '', {
        R_1:  createStats("Rychlost kouzla:",  "5%", "8%", "12%", "17%", "25%", "30%", "40%", "45%", "50%", "55%"),
        R_M1: createStats(),
        R_2: createStats("Šance:",  "-", "-", "-", "-", "-", "-", "-",          "10%",    "10%",   "5%"),
        R_3: createStats("Cena:",   "-", "-", "-", "-", "-", "-", "-",          "2kkk",   "3kkk",  "5kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:",  "", "", "", "", "", "", "",     "192x",   "256x",   "384x"),
        R_5: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
        R_6: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_M1: createImage(),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage(),
        IMG_4: createImage("", "", "", "", "", "", "", "", "./items/Střelný prach.png", "./items/Střelný prach.png", "./items/Střelný prach.png"),
        IMG_5: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png"),
        IMG_6: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png"),
      }),
      createEquipmentItem(10, 'Kámen proti válečníkům', 'https://img.m2icondb.com/28003.png', '', {
        R_1:  createStats("Síla proti proti válečníkům:",  "5%", "8%", "12%", "17%", "25%", "30%", "40%", "50%", "60%", "70%"),
        R_M1: createStats(),
        R_2: createStats("Šance:",  "-", "-", "-", "-", "-", "-", "-",          "10%",    "10%",   "5%"),
        R_3: createStats("Cena:",   "-", "-", "-", "-", "-", "-", "-",          "2kkk",   "3kkk",  "5kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:",  "", "", "", "", "", "", "",     "192x",   "256x",   "384x"),
        R_5: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
        R_6: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_M1: createImage(),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage(),
        IMG_4: createImage("", "", "", "", "", "", "", "", "./items/Střelný prach.png", "./items/Střelný prach.png", "./items/Střelný prach.png"),
        IMG_5: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png"),
        IMG_6: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png"),
      }),
      createEquipmentItem(10, 'Kámen proti ninjům', 'https://img.m2icondb.com/28004.png', '', {
        R_1:  createStats("Síla proti ninjům:",  "5%", "8%", "12%", "17%", "25%", "30%", "40%", "50%", "60%", "70%"),
        R_M1: createStats(),
        R_2: createStats("Šance:",  "-", "-", "-", "-", "-", "-", "-",          "10%",    "10%",   "5%"),
        R_3: createStats("Cena:",   "-", "-", "-", "-", "-", "-", "-",          "2kkk",   "3kkk",  "5kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:",  "", "", "", "", "", "", "",     "192x",   "256x",   "384x"),
        R_5: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
        R_6: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_M1: createImage(),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage(),
        IMG_4: createImage("", "", "", "", "", "", "", "", "./items/Střelný prach.png", "./items/Střelný prach.png", "./items/Střelný prach.png"),
        IMG_5: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png"),
        IMG_6: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png"),
      }),
      createEquipmentItem(10, 'Kámen proti surům', 'https://img.m2icondb.com/28005.png', '', {
        R_1:  createStats("Síla proti surům:",  "5%", "8%", "12%", "17%", "25%", "30%", "40%", "50%", "60%", "70%"),
        R_M1: createStats(),
        R_2: createStats("Šance:",  "-", "-", "-", "-", "-", "-", "-",          "10%",    "10%",   "5%"),
        R_3: createStats("Cena:",   "-", "-", "-", "-", "-", "-", "-",          "2kkk",   "3kkk",  "5kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:",  "", "", "", "", "", "", "",     "192x",   "256x",   "384x"),
        R_5: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
        R_6: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_M1: createImage(),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage(),
        IMG_4: createImage("", "", "", "", "", "", "", "", "./items/Střelný prach.png", "./items/Střelný prach.png", "./items/Střelný prach.png"),
        IMG_5: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png"),
        IMG_6: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png"),
      }),
      createEquipmentItem(10, 'Kámen proti šamanům', 'https://img.m2icondb.com/28006.png', '', {
        R_1:  createStats("Síla proti šamanům:",  "5%", "8%", "12%", "17%", "25%", "30%", "40%", "50%", "60%", "70%"),
        R_M1: createStats(),
        R_2: createStats("Šance:",  "-", "-", "-", "-", "-", "-", "-",          "10%",    "10%",   "5%"),
        R_3: createStats("Cena:",   "-", "-", "-", "-", "-", "-", "-",          "2kkk",   "3kkk",  "5kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:",  "", "", "", "", "", "", "",     "192x",   "256x",   "384x"),
        R_5: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
        R_6: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_M1: createImage(),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage(),
        IMG_4: createImage("", "", "", "", "", "", "", "", "./items/Střelný prach.png", "./items/Střelný prach.png", "./items/Střelný prach.png"),
        IMG_5: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png"),
        IMG_6: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png"),
      }),
      createEquipmentItem(10, 'Kámen nestvůr', 'https://img.m2icondb.com/28007.png', '', {
        R_1:  createStats("Silný proti příšerám:",  "1%", "2%", "3%", "5%", "8%", "10%", "13%", "16%", "20%", "25%"),
        R_M1: createStats(),
        R_2: createStats("Šance:",  "-", "-", "-", "-", "-", "-", "-",          "10%",    "10%",   "5%"),
        R_3: createStats("Cena:",   "-", "-", "-", "-", "-", "-", "-",          "2kkk",   "3kkk",  "5kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:",  "", "", "", "", "", "", "",     "192x",   "256x",   "384x"),
        R_5: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
        R_6: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_M1: createImage("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "", "", "", "", "", "./items/Střelný prach.png", "./items/Střelný prach.png", "./items/Střelný prach.png"),
        IMG_5: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png"),
        IMG_6: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png"),
      }),
      createEquipmentItem(10, 'Kámen vyhýbání', 'https://img.m2icondb.com/28008.png', '', {
        R_1:  createStats("Šance odvrátit útok:",  "1%", "2%", "3%", "5%", "8%", "10%", "12%", "14%", "16%", "18%"),
        R_M1: createStats(),
        R_2: createStats("Šance:",  "-", "-", "-", "-", "-", "-", "-",          "10%",    "10%",   "5%"),
        R_3: createStats("Cena:",   "-", "-", "-", "-", "-", "-", "-",          "2kkk",   "3kkk",  "5kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:",  "", "", "", "", "", "", "",     "192x",   "256x",   "384x"),
        R_5: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
        R_6: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_M1: createImage("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "", "", "", "", "", "./items/Střelný prach.png", "./items/Střelný prach.png", "./items/Střelný prach.png"),
        IMG_5: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png"),
        IMG_6: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png"),
      }),
      createEquipmentItem(10, 'Kámen schýlení', 'https://img.m2icondb.com/28009.png', '', {
        R_1:  createStats("Šance vyhnout se šípům:",  "1%", "2%", "3%", "5%", "8%", "10%", "12%", "-", "-", "-"),
        R_11: createStats("Šance na návrat z podsvětí:",            "-", "-", "-", "-", "-", "-", "-", "1%", "2%", "5%"),
        R_M1: createStats(),
        R_2: createStats("Šance:",  "-", "-", "-", "-", "-", "-", "-",          "10%",    "10%",   "5%"),
        R_3: createStats("Cena:",   "-", "-", "-", "-", "-", "-", "-",          "2kkk",   "3kkk",  "5kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:",  "", "", "", "", "", "", "",     "192x",   "256x",   "384x"),
        R_5: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
        R_6: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_11: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_M1: createImage("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "", "", "", "", "", "./items/Střelný prach.png", "./items/Střelný prach.png", "./items/Střelný prach.png"),
        IMG_5: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png"),
        IMG_6: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png"),
      }),
      createEquipmentItem(10, 'Kámen magie', 'https://img.m2icondb.com/28010.png', '', {
        R_1:  createStats("Silný proti kamenům:",  "1%", "2%", "3%", "5%", "8%", "10%", "13%", "16%", "20%", "25%"),
        R_M1: createStats(),
        R_2: createStats("Šance:",  "-", "-", "-", "-", "-", "-", "-",          "10%",    "10%",   "5%"),
        R_3: createStats("Cena:",   "-", "-", "-", "-", "-", "-", "-",          "2kkk",   "3kkk",  "5kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:",  "", "", "", "", "", "", "",     "192x",   "256x",   "384x"),
        R_5: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
        R_6: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_M1: createImage("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "", "", "", "", "", "./items/Střelný prach.png", "./items/Střelný prach.png", "./items/Střelný prach.png"),
        IMG_5: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png"),
        IMG_6: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png"),
      }),
      createEquipmentItem(10, 'Kámen vitality', 'https://img.m2icondb.com/28011.png', '', {
        R_1:  createStats("Max. ZB:",  "+50", "+100", "+150", "+500", "+1000", "+2000", "+4000", "+6000", "+8000", "+10000"),
        R_M1: createStats(),
        R_2: createStats("Šance:",  "-", "-", "-", "-", "-", "-", "-",          "10%",    "10%",   "5%"),
        R_3: createStats("Cena:",   "-", "-", "-", "-", "-", "-", "-",          "2kkk",   "3kkk",  "5kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:",  "", "", "", "", "", "", "",     "192x",   "256x",   "384x"),
        R_5: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
        R_6: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_M1: createImage("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "", "", "", "", "", "./items/Střelný prach.png", "./items/Střelný prach.png", "./items/Střelný prach.png"),
        IMG_5: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png"),
        IMG_6: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png"),
      }),
      createEquipmentItem(10, 'Kámen ochrany', 'https://img.m2icondb.com/28012.png', '', {
        R_1:  createStats("Max. ZB:",  "+2", "+4", "+6", "+10", "+15", "+60", "+100", "-", "-", "-"),
        R_11: createStats("Ochrana proti bossům:",            "-", "-", "-", "-", "-", "-", "-", "3%", "6%", "10%"),
        R_M1: createStats(),
        R_2: createStats("Šance:",  "-", "-", "-", "-", "-", "-", "-",          "10%",    "10%",   "5%"),
        R_3: createStats("Cena:",   "-", "-", "-", "-", "-", "-", "-",          "2kkk",   "3kkk",  "5kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:",  "", "", "", "", "", "", "",     "192x",   "256x",   "384x"),
        R_5: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
        R_6: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_11: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_M1: createImage("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "", "", "", "", "", "./items/Střelný prach.png", "./items/Střelný prach.png", "./items/Střelný prach.png"),
        IMG_5: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png"),
        IMG_6: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png"),
      }),
      createEquipmentItem(10, 'Kámen spěchu', 'https://img.m2icondb.com/28013.png', '', {
        R_1:  createStats("Rychlost pohybu:",  "5%", "10%", "15%", "20%", "30%", "35%", "50%", "50%", "50%", "50%"),
        R_M1: createStats(),
        R_2: createStats("Šance:",  "-", "-", "-", "-", "-", "-", "-",          "10%",    "10%",   "5%"),
        R_3: createStats("Cena:",   "-", "-", "-", "-", "-", "-", "-",          "2kkk",   "3kkk",  "5kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:",  "", "", "", "", "", "", "",     "192x",   "256x",   "384x"),
        R_5: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
        R_6: createStats("",                    "", "", "", "", "", "", "",     "75x",    "100x",   "150x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", "", "", "", ""),
        IMG_M1: createImage("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "", "", "", "", "", "./items/Střelný prach.png", "./items/Střelný prach.png", "./items/Střelný prach.png"),
        IMG_5: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png", "./items/Úlomek kamene džungle.png"),
        IMG_6: createImage("", "", "", "", "", "", "", "", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png", "./items/Úlomek kamene škeble.png"),
      }),

  ];
