import { createStats, createImage, createEquipmentItem } from './funkceTabulkos.js';

  export const krystalyData = [      
    createEquipmentItem(7, 'Krystal Lunaris', './items/Krystal Lunaris.png', 'Lze získat z cechovního World Bosse - Bestie', {
        R_1: createStats("Průměrná škoda:", "1%", "1%", "2%", "2%", "3%", "4%", "6%"),
        R_M1: createStats(),
        R_2: createStats("Šance:", "-", "40%", "50%", "60%", "70%", "80%", "90%"),
        R_3: createStats("Cena:", "-", "500kk", "400kk", "800kk", "1,2kkk", "1,6kkk", "2kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:", "-", "-", "+0", "+1", "+2", "+3", "+4"),
        R_5: createStats("", "-", "1x", "2x", "4x", "8x", "16x", "32x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "./items/Krystal Lunaris.png", "./items/Krystal Lunaris.png", "./items/Krystal Lunaris.png", "./items/Krystal Lunaris.png", "./items/Krystal Lunaris.png"),
        IMG_5: createImage("", "", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png"),
    }),
    createEquipmentItem(7, 'Krystal Glorikon', './items/Krystal Glorikon.png', 'Lze získat z cechovního World Bosse - Bestie', {
        R_1: createStats("Silný proti příšerám:", "1%", "2%", "3%", "4%", "5%", "7%", "10%"),
        R_M1: createStats(),
        R_2: createStats("Šance:", "-", "40%", "50%", "60%", "70%", "80%", "90%"),
        R_3: createStats("Cena:", "-", "500kk", "400kk", "800kk", "1,2kkk", "1,6kkk", "2kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:", "-", "-", "+0", "+1", "+2", "+3", "+4"),
        R_5: createStats("", "-", "1x", "2x", "4x", "8x", "16x", "32x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "./items/Krystal Glorikon.png", "./items/Krystal Glorikon.png", "./items/Krystal Glorikon.png", "./items/Krystal Glorikon.png", "./items/Krystal Glorikon.png"),
        IMG_5: createImage("", "", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png"),
    }),
    createEquipmentItem(7, 'Krystal Mercurion', './items/Krystal Mercurion.png', 'Lze získat z cechovního World Bosse - Bestie', {
        R_1: createStats("Poškození schopností:", "1%", "1%", "2%", "2%", "3%", "4%", "6%"),
        R_M1: createStats(),
        R_2: createStats("Šance:", "-", "40%", "50%", "60%", "70%", "80%", "90%"),
        R_3: createStats("Cena:", "-", "500kk", "400kk", "800kk", "1,2kkk", "1,6kkk", "2kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:", "-", "-", "+0", "+1", "+2", "+3", "+4"),
        R_5: createStats("", "-", "1x", "2x", "4x", "8x", "16x", "32x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "./items/Krystal Mercurion.png", "./items/Krystal Mercurion.png", "./items/Krystal Mercurion.png", "./items/Krystal Mercurion.png", "./items/Krystal Mercurion.png"),
        IMG_5: createImage("", "", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png"),
    }),
    createEquipmentItem(7, 'Krystal Drakolith', './items/Krystal Drakolith.png', 'Lze získat z cechovního World Bosse - Bestie', {
        R_1: createStats("Silný proti lidem:", "1%", "2%", "3%", "4%", "5%", "7%", "10%"),
        R_M1: createStats(),
        R_2: createStats("Šance:", "-", "40%", "50%", "60%", "70%", "80%", "90%"),
        R_3: createStats("Cena:", "-", "500kk", "400kk", "800kk", "1,2kkk", "1,6kkk", "2kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:", "-", "-", "+0", "+1", "+2", "+3", "+4"),
        R_5: createStats("", "-", "1x", "2x", "4x", "8x", "16x", "32x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "./items/Krystal Drakolith.png", "./items/Krystal Drakolith.png", "./items/Krystal Drakolith.png", "./items/Krystal Drakolith.png", "./items/Krystal Drakolith.png"),
        IMG_5: createImage("", "", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png"),
    }),
    createEquipmentItem(7, 'Krystal Solaryt', './items/Krystal Solaryt.png', 'Lze získat z cechovního World Bosse - Bestie', {
        R_1: createStats("Max. ZB:", "+250", "+500", "+900", "+1400", "+2100", "+3000", "+4000"),
        R_M1: createStats(),
        R_2: createStats("Šance:", "-", "40%", "50%", "60%", "70%", "80%", "90%"),
        R_3: createStats("Cena:", "-", "500kk", "400kk", "800kk", "1,2kkk", "1,6kkk", "2kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:", "-", "-", "+0", "+1", "+2", "+3", "+4"),
        R_5: createStats("", "-", "1x", "2x", "4x", "8x", "16x", "32x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "./items/Krystal Solaryt.png", "./items/Krystal Solaryt.png", "./items/Krystal Solaryt.png", "./items/Krystal Solaryt.png", "./items/Krystal Solaryt.png"),
        IMG_5: createImage("", "", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png"),
    }),
    createEquipmentItem(7, 'Krystal Celestium', './items/Krystal Celestium.png', 'Lze získat z cechovního World Bosse - Bestie', {
        R_1: createStats("Síla:", "1", "1", "2", "2", "3", "5", "8"),
        R_M1: createStats(),
        R_2: createStats("Šance:", "-", "40%", "50%", "60%", "70%", "80%", "90%"),
        R_3: createStats("Cena:", "-", "500kk", "400kk", "800kk", "1,2kkk", "1,6kkk", "2kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:", "-", "-", "+0", "+1", "+2", "+3", "+4"),
        R_5: createStats("", "-", "1x", "2x", "4x", "8x", "16x", "32x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "./items/Krystal Celestium.png", "./items/Krystal Celestium.png", "./items/Krystal Celestium.png", "./items/Krystal Celestium.png", "./items/Krystal Celestium.png"),
        IMG_5: createImage("", "", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png"),
    }),
    createEquipmentItem(7, 'Krystal Aetherion', './items/Krystal Aetherion.png', 'Lze získat z cechovního World Bosse - Bestie', {
        R_1: createStats("Inteligence:", "1", "1", "2", "2", "3", "5", "8"),
        R_M1: createStats(),
        R_2: createStats("Šance:", "-", "40%", "50%", "60%", "70%", "80%", "90%"),
        R_3: createStats("Cena:", "-", "500kk", "400kk", "800kk", "1,2kkk", "1,6kkk", "2kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:", "-", "-", "+0", "+1", "+2", "+3", "+4"),
        R_5: createStats("", "-", "1x", "2x", "4x", "8x", "16x", "32x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "./items/Krystal Aetherion.png", "./items/Krystal Aetherion.png", "./items/Krystal Aetherion.png", "./items/Krystal Aetherion.png", "./items/Krystal Aetherion.png"),
        IMG_5: createImage("", "", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png"),
    }),
    createEquipmentItem(7, 'Krystal Eldorium', './items/Krystal Eldorium.png', 'Lze získat z cechovního World Bosse - Bestie', {
        R_1: createStats("Pohyblivost:", "1", "1", "2", "2", "3", "5", "8"),
        R_M1: createStats(),
        R_2: createStats("Šance:", "-", "40%", "50%", "60%", "70%", "80%", "90%"),
        R_3: createStats("Cena:", "-", "500kk", "400kk", "800kk", "1,2kkk", "1,6kkk", "2kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:", "-", "-", "+0", "+1", "+2", "+3", "+4"),
        R_5: createStats("", "-", "1x", "2x", "4x", "8x", "16x", "32x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "./items/Krystal Eldorium.png", "./items/Krystal Eldorium.png", "./items/Krystal Eldorium.png", "./items/Krystal Eldorium.png", "./items/Krystal Eldorium.png"),
        IMG_5: createImage("", "", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png"),
    }),
    createEquipmentItem(7, 'Krystal Auralith', './items/Krystal Auralith.png', 'Lze získat z cechovního World Bosse - Bestie', {
        R_1: createStats("Vitalita:", "1", "1", "2", "2", "3", "5", "8"),
        R_M1: createStats(),
        R_2: createStats("Šance:", "-", "40%", "50%", "60%", "70%", "80%", "90%"),
        R_3: createStats("Cena:", "-", "500kk", "400kk", "800kk", "1,2kkk", "1,6kkk", "2kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:", "-", "-", "+0", "+1", "+2", "+3", "+4"),
        R_5: createStats("", "-", "1x", "2x", "4x", "8x", "16x", "32x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "./items/Krystal Auralith.png", "./items/Krystal Auralith.png", "./items/Krystal Auralith.png", "./items/Krystal Auralith.png", "./items/Krystal Auralith.png"),
        IMG_5: createImage("", "", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png"),
    }),
    createEquipmentItem(7, 'Krystal Nebulion', './items/Krystal Nebulion.png', 'Lze získat z cechovního World Bosse - Bestie', {
        R_1: createStats("Síla proti větru:", "1%", "2%", "3%", "4%", "5%", "7%", "10%"),
        R_M1: createStats(),
        R_2: createStats("Šance:", "-", "40%", "50%", "60%", "70%", "80%", "90%"),
        R_3: createStats("Cena:", "-", "500kk", "400kk", "800kk", "1,2kkk", "1,6kkk", "2kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:", "-", "-", "+0", "+1", "+2", "+3", "+4"),
        R_5: createStats("", "-", "1x", "2x", "4x", "8x", "16x", "32x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "./items/Krystal Nebulion.png", "./items/Krystal Nebulion.png", "./items/Krystal Nebulion.png", "./items/Krystal Nebulion.png", "./items/Krystal Nebulion.png"),
        IMG_5: createImage("", "", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png"),
    }),
    createEquipmentItem(7, 'Krystal Thundralis', './items/Krystal Thundralis.png', 'Lze získat z cechovního World Bosse - Bestie', {
        R_1: createStats("Síla proti temnotě:", "1%", "2%", "3%", "4%", "5%", "7%", "10%"),
        R_M1: createStats(),
        R_2: createStats("Šance:", "-", "40%", "50%", "60%", "70%", "80%", "90%"),
        R_3: createStats("Cena:", "-", "500kk", "400kk", "800kk", "1,2kkk", "1,6kkk", "2kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:", "-", "-", "+0", "+1", "+2", "+3", "+4"),
        R_5: createStats("", "-", "1x", "2x", "4x", "8x", "16x", "32x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "./items/Krystal Thundralis.png", "./items/Krystal Thundralis.png", "./items/Krystal Thundralis.png", "./items/Krystal Thundralis.png", "./items/Krystal Thundralis.png"),
        IMG_5: createImage("", "", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png"),
    }),
    createEquipmentItem(7, 'Krystal Astralith', './items/Krystal Astralith.png', 'Lze získat z cechovního World Bosse - Bestie', {
        R_1: createStats("Síla proti ledu:", "1%", "2%", "3%", "4%", "5%", "7%", "10%"),
        R_M1: createStats(),
        R_2: createStats("Šance:", "-", "40%", "50%", "60%", "70%", "80%", "90%"),
        R_3: createStats("Cena:", "-", "500kk", "400kk", "800kk", "1,2kkk", "1,6kkk", "2kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:", "-", "-", "+0", "+1", "+2", "+3", "+4"),
        R_5: createStats("", "-", "1x", "2x", "4x", "8x", "16x", "32x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "./items/Krystal Astralith.png", "./items/Krystal Astralith.png", "./items/Krystal Astralith.png", "./items/Krystal Astralith.png", "./items/Krystal Astralith.png"),
        IMG_5: createImage("", "", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png"),
    }),
    createEquipmentItem(7, 'Krystal Vesperion', './items/Krystal Vesperion.png', 'Lze získat z cechovního World Bosse - Bestie', {
        R_1: createStats("Síla proti zemi:", "1%", "2%", "3%", "4%", "5%", "7%", "10%"),
        R_M1: createStats(),
        R_2: createStats("Šance:", "-", "40%", "50%", "60%", "70%", "80%", "90%"),
        R_3: createStats("Cena:", "-", "500kk", "400kk", "800kk", "1,2kkk", "1,6kkk", "2kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:", "-", "-", "+0", "+1", "+2", "+3", "+4"),
        R_5: createStats("", "-", "1x", "2x", "4x", "8x", "16x", "32x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "./items/Krystal Vesperion.png", "./items/Krystal Vesperion.png", "./items/Krystal Vesperion.png", "./items/Krystal Vesperion.png", "./items/Krystal Vesperion.png"),
        IMG_5: createImage("", "", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png"),
    }),
    createEquipmentItem(7, 'Krystal Solunite', './items/Krystal Solunite.png', 'Lze získat z cechovního World Bosse - Bestie', {
        R_1: createStats("Síla proti blesku:", "1%", "2%", "3%", "4%", "5%", "7%", "10%"),
        R_M1: createStats(),
        R_2: createStats("Šance:", "-", "40%", "50%", "60%", "70%", "80%", "90%"),
        R_3: createStats("Cena:", "-", "500kk", "400kk", "800kk", "1,2kkk", "1,6kkk", "2kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:", "-", "-", "+0", "+1", "+2", "+3", "+4"),
        R_5: createStats("", "-", "1x", "2x", "4x", "8x", "16x", "32x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "./items/Krystal Solunite.png", "./items/Krystal Solunite.png", "./items/Krystal Solunite.png", "./items/Krystal Solunite.png", "./items/Krystal Solunite.png"),
        IMG_5: createImage("", "", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png"),
    }),
    createEquipmentItem(7, 'Krystal Netherite', './items/Krystal Netherite.png', 'Lze získat z cechovního World Bosse - Bestie', {
        R_1: createStats("Síla proti ohni:", "1%", "2%", "3%", "4%", "5%", "7%", "10%"),
        R_M1: createStats(),
        R_2: createStats("Šance:", "-", "40%", "50%", "60%", "70%", "80%", "90%"),
        R_3: createStats("Cena:", "-", "500kk", "400kk", "800kk", "1,2kkk", "1,6kkk", "2kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:", "-", "-", "+0", "+1", "+2", "+3", "+4"),
        R_5: createStats("", "-", "1x", "2x", "4x", "8x", "16x", "32x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "./items/Krystal Netherite.png", "./items/Krystal Netherite.png", "./items/Krystal Netherite.png", "./items/Krystal Netherite.png", "./items/Krystal Netherite.png"),
        IMG_5: createImage("", "", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png"),
    }),
    createEquipmentItem(7, 'Krystal Zirconis', './items/Krystal Zirconis.png', 'Lze získat z cechovního World Bosse - Bestie', {
        R_1: createStats("Rychlost kouzla:", "2%", "4%", "6%", "8%", "10%", "14%", "20%"),
        R_M1: createStats(),
        R_2: createStats("Šance:", "-", "40%", "50%", "60%", "70%", "80%", "90%"),
        R_3: createStats("Cena:", "-", "500kk", "400kk", "800kk", "1,2kkk", "1,6kkk", "2kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:", "-", "-", "+0", "+1", "+2", "+3", "+4"),
        R_5: createStats("", "-", "1x", "2x", "4x", "8x", "16x", "32x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "./items/Krystal Zirconis.png", "./items/Krystal Zirconis.png", "./items/Krystal Zirconis.png", "./items/Krystal Zirconis.png", "./items/Krystal Zirconis.png"),
        IMG_5: createImage("", "", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png"),
    }),
    createEquipmentItem(7, 'Krystal Nyxium', './items/Krystal Nyxium.png', 'Lze získat z cechovního World Bosse - Bestie', {
        R_1: createStats("Rychlost pohybu:", "2%", "4%", "6%", "8%", "10%", "14%", "20%"),
        R_M1: createStats(),
        R_2: createStats("Šance:", "-", "40%", "50%", "60%", "70%", "80%", "90%"),
        R_3: createStats("Cena:", "-", "500kk", "400kk", "800kk", "1,2kkk", "1,6kkk", "2kkk"),
        R_M2: createStats(),
        R_4: createStats("Potřebné předměty:", "-", "-", "+0", "+1", "+2", "+3", "+4"),
        R_5: createStats("", "-", "1x", "2x", "4x", "8x", "16x", "32x"),
      }, {
        IMG_1: createImage("", "", "", "", "", "", "", ""),
        IMG_M1: createStats("", "", "", "", "", "", "", ""),
        IMG_2: createImage("", "", "", "", "", "", "", ""),
        IMG_3: createImage("", "", "", "", "", "", "", ""),
        IMG_M2: createImage("", "", "", "", "", "", "", ""),
        IMG_4: createImage("", "", "", "./items/Krystal Nyxium.png", "./items/Krystal Nyxium.png", "./items/Krystal Nyxium.png", "./items/Krystal Nyxium.png", "./items/Krystal Nyxium.png"),
        IMG_5: createImage("", "", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png", "./items/Krystalový prach.png"),
    }),
  ];
